import Head from 'next/head'
import Image from 'next/image'
import Link  from 'next/link'
import styles from '../styles/Home.module.css'

export default function index() {
  return (
    
    <div className={styles.container}>
      <Head>
        <title>Receitas Rápidas</title>
        <meta name="description" content="Generated by create next app" />
        <a rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <div className={styles.grid}>
       <p className={styles.card}>
         <h1 >
          Seja bem vindo <a href='/home'>ao nosso site!</a>
         </h1>

         <p className={styles.subtitle}>
          Aqui você irá desfrutar de <br/>comidas deliciosas, hlrgfuirg{' '}
          <code className={styles.code}></code>
         </p>

         
        </p>
        <Image src="/" alt="Vercel Logo" width={72} height={16} />
        </ div>
      </main>
    </div>
  
  )
}
